# Generated by Django 4.2.20 on 2025-05-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ra", models.PositiveIntegerField(unique=True, verbose_name="RA")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("curso", models.CharField(max_length=100, verbose_name="Curso")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("data_nasc", models.DateField(verbose_name="Data de Nascimento")),
            ],
        ),
        migrations.CreateModel(
            name="Indicativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("indicativo", models.BooleanField(verbose_name="Indicativo")),
            ],
        ),
        migrations.CreateModel(
            name="Laudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("data", models.DateField(verbose_name="Data do Laudo")),
            ],
        ),
        migrations.CreateModel(
            name="Napne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateField(verbose_name="Data de Criação")),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
            ],
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "siape",
                    models.PositiveIntegerField(unique=True, verbose_name="SIAPE"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("tipo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "napne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.napne",
                        verbose_name="NAPNE",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="laudo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="paginas.laudo",
                verbose_name="Laudo",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paginas.responsavel",
                verbose_name="Responsável",
            ),
        ),
    ]
