# Generated by Django 5.2.1 on 2025-05-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicativo',
            old_name='date',
            new_name='data',
        ),
    ]
