# Generated by Django 4.2.20 on 2025-08-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="aluno",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emprestimos",
                to="paginas.aluno",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(default="2025-08-20"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="servidor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="paginas.servidor",
            ),
            preserve_default=False,
        ),
    ]
