# Generated by Django 4.2.20 on 2025-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_emprestimo_aluno_emprestimo_data_devolucao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="aluno_confirmacao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="aluno_data_confirmacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="emprestado",
            field=models.BooleanField(default=True),
        ),
    ]
