# Generated by Django 5.2.1 on 2025-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_rename_date_indicativo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('emprestimo', models.BooleanField(verbose_name='Emprestimo')),
            ],
        ),
        migrations.DeleteModel(
            name='Indicativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='laudo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='napne',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='responsavel',
        ),
        migrations.DeleteModel(
            name='Interacoes',
        ),
        migrations.DeleteModel(
            name='Laudo',
        ),
        migrations.DeleteModel(
            name='Napne',
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
