# Generated by Django 4.2.20 on 2025-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0003_emprestimo_aluno_confirmacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="ano",
            field=models.IntegerField(verbose_name="Ano"),
        ),
    ]
