# Generated by Django 5.2.1 on 2025-05-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_emprestimo_delete_indicativo_remove_aluno_laudo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
    ]
