# Generated by Django 5.2.7 on 2025-11-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_aluno_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='rg',
        ),
    ]
