# Generated by Django 4.2.23 on 2025-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0005_remove_aluno_rg"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="confirmacao_devolucao",
            field=models.BooleanField(default=False),
        ),
    ]
