# Generated by Django 5.2.7 on 2025-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_emprestimo_confirmacao_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='categoria',
            field=models.CharField(choices=[('material_estudo', 'Material de Estudo'), ('material_esportivo', 'Material Esportivo'), ('equipamento_eletronico', 'Equipamento Eletrônico'), ('ferramenta', 'Ferramenta'), ('livro', 'Livro'), ('uniforme', 'Uniforme'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Categoria do Item'),
        ),
    ]
